# Generated by Django 4.0.3 on 2022-03-12 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ville", models.CharField(default="Nouakchott", max_length=100)),
                ("quartier", models.CharField(default="Tevrag Zeina", max_length=200)),
                ("longitude", models.CharField(blank=True, max_length=500, null=True)),
                ("latitude", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "longitudeDelta",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "latitudeDelta",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("description", models.TextField()),
            ],
            options={
                "unique_together": {("ville", "quartier", "description")},
            },
        ),
        migrations.CreateModel(
            name="Arena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("is_partener", models.BooleanField(default=False)),
                ("note", models.IntegerField()),
                (
                    "adress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.adress"
                    ),
                ),
            ],
            options={
                "verbose_name": "Arena",
                "verbose_name_plural": "Arena",
            },
        ),
        migrations.CreateModel(
            name="BankilyPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("5", "5 vs 5"),
                            ("6", "6 vs 6"),
                            ("7", "7 vs 7"),
                            ("8", "8 vs 8"),
                        ],
                        default="5",
                        max_length=10,
                    ),
                ),
                ("score", models.CharField(default="NA", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="MasrviPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StripePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_id", models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="TimeStampCreation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="InformationDetails",
            fields=[
                (
                    "timestampcreation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.timestampcreation",
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=20)),
                ("email_adress", models.EmailField(blank=True, max_length=254)),
            ],
            bases=("api.timestampcreation",),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "timestampcreation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.timestampcreation",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("amount", models.IntegerField()),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            bases=("api.timestampcreation",),
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("LUNDI", "LUNDI"),
                            ("MARDI", "MARDI"),
                            ("MERCREDI", "MERCREDI"),
                            ("JEUDI", "JEUDI"),
                            ("VENDREDI", "VENDREDI"),
                            ("SAMEDI", "SAMEDI"),
                            ("DIMANCHE", "DIMANCHE"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_hour", models.IntegerField()),
                ("start_minute", models.IntegerField()),
                ("end_hour", models.IntegerField()),
                ("end_minute", models.IntegerField()),
                ("available", models.BooleanField(default=True)),
                (
                    "arena",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.arena"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "informationdetails_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.informationdetails",
                    ),
                ),
            ],
            bases=("api.informationdetails",),
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "informationdetails_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.informationdetails",
                    ),
                ),
            ],
            bases=("api.informationdetails",),
        ),
        migrations.CreateModel(
            name="StarOfTheGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.game"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.player"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_be_refund", models.BooleanField(default=False)),
                ("refunded", models.BooleanField(default=False)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.game"
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.payment"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.player"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="organised_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="captain",
                to="api.player",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="players",
            field=models.ManyToManyField(related_name="game", to="api.player"),
        ),
        migrations.AddField(
            model_name="arena",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.manager"
            ),
        ),
    ]
