# Generated by Django 3.2.12 on 2022-04-09 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="manager",
            unique_together={("phone_number",)},
        ),
        migrations.AlterUniqueTogether(
            name="player",
            unique_together={("phone_number",)},
        ),
    ]
