# Generated by Django 3.2.12 on 2022-05-29 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20220409_0200"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "timestampcreation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.timestampcreation",
                    ),
                ),
                ("url", models.CharField(max_length=500)),
                (
                    "arena",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medias",
                        to="api.arena",
                    ),
                ),
            ],
            bases=("api.timestampcreation",),
        ),
    ]
