# Generated by Django 3.2.12 on 2022-06-25 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_arena_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="organised_by",
        ),
        migrations.AddField(
            model_name="game",
            name="arena",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="api.arena",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="captain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="captains",
                to="api.player",
            ),
        ),
        migrations.AlterField(
            model_name="availability",
            name="arena",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="api.arena",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="players",
            field=models.ManyToManyField(related_name="games", to="api.Player"),
        ),
    ]
