# Generated by Django 3.2.12 on 2022-06-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auto_20220625_1424"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adress",
            options={"verbose_name_plural": "Adresses"},
        ),
    ]
