# Generated by Django 3.2.12 on 2022-06-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_adress_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="availability",
            name="price",
            field=models.IntegerField(default=5000),
        ),
    ]
