# Generated by Django 3.2.12 on 2022-08-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_availability_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="amount",
            field=models.IntegerField(default=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="code",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("0", "Waiting for paiment"),
                    ("1", "Validated ✅"),
                    ("2", "Canceled ❌"),
                ],
                default="0",
                max_length=10,
            ),
        ),
    ]
