# Generated by Django 3.2.12 on 2022-08-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_auto_20220808_1706"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="profile",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="profile",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
