# Generated by Django 3.2.12 on 2022-08-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_auto_20220814_2218"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="blocked",
            field=models.BooleanField(default=False),
        ),
    ]
