# Generated by Django 3.2.12 on 2022-08-17 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_game_blocked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arena",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arenas",
                to="api.manager",
            ),
        ),
    ]
