# Generated by Django 3.2.12 on 2022-08-22 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_arena_manager"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArenaFiveSettings",
            fields=[
                (
                    "timestampcreation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.timestampcreation",
                    ),
                ),
                ("portable", models.CharField(blank=True, max_length=20, null=True)),
                ("fix_number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "bankily_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "maservi_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "twitter_link",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "facebook_link",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "whatsapp_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
            bases=("api.timestampcreation",),
        ),
    ]
