# Generated by Django 3.2.12 on 2022-10-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_arenafivesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="adress",
            name="description_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="adress",
            name="description_fr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="adress",
            name="quartier_ar",
            field=models.CharField(default="Tevrag Zeina", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="adress",
            name="quartier_fr",
            field=models.CharField(default="Tevrag Zeina", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="adress",
            name="ville_ar",
            field=models.CharField(default="Nouakchott", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="adress",
            name="ville_fr",
            field=models.CharField(default="Nouakchott", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="arena",
            name="description_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="arena",
            name="description_fr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="arena",
            name="slug_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="arena",
            name="slug_fr",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
