# Generated by Django 3.2.12 on 2022-10-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_auto_20221009_0036"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="exponent_push_token",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="exponent_push_token",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
