# Generated by Django 3.2.12 on 2022-10-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_arenafivesettings_bankily_merchant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankilypayment",
            name="operation_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
