# Generated by Django 3.2.12 on 2022-10-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20221021_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='cancel_limit',
            field=models.IntegerField(default=24, help_text='The threshold for a cancel game'),
        ),
        migrations.AddField(
            model_name='manager',
            name='bankily_number',
            field=models.CharField(default='00', max_length=20),
            preserve_default=False,
        ),
    ]
