# Generated by Django 3.2.12 on 2022-12-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_auto_20221027_1307"),
    ]

    operations = [
        migrations.AddField(
            model_name="arena",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="arena",
            name="order",
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name="timestampcreation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="timestampcreation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
